/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerInquiry {
  'id' : InquiryId,
  'customerName' : string,
  'productId' : ProductId,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'companyName' : [] | [string],
  'phone' : string,
  'quantityRequired' : bigint,
}
export interface FabricProduct {
  'id' : ProductId,
  'minOrderQuantity' : bigint,
  'weightGSM' : bigint,
  'fabricType' : string,
  'name' : string,
  'color' : string,
  'imageFilename' : string,
  'description' : string,
  'pricePerMeter' : number,
  'width' : ProductWidth,
}
export type InquiryId = bigint;
export type ProductId = bigint;
export type ProductWidth = { 'centimeters' : bigint } |
  { 'inches' : bigint };
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'company' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      bigint,
      ProductWidth,
      bigint,
      number,
      string,
    ],
    ProductId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllInquiries' : ActorMethod<[], Array<CustomerInquiry>>,
  'getAllProducts' : ActorMethod<[], Array<FabricProduct>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProduct' : ActorMethod<[ProductId], FabricProduct>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitInquiry' : ActorMethod<
    [string, string, string, [] | [string], ProductId, bigint, string],
    InquiryId
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];