/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerInquiry {
  'id' : InquiryId,
  'customerName' : string,
  'productId' : ProductId,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'companyName' : [] | [string],
  'phone' : string,
  'quantityRequired' : bigint,
}
export interface FabricProduct {
  'id' : ProductId,
  'minOrderQuantity' : bigint,
  'weightGSM' : bigint,
  'fabricType' : string,
  'widthCM' : bigint,
  'name' : string,
  'color' : string,
  'imageFilename' : string,
  'description' : string,
  'pricePerMeter' : number,
}
export type InquiryId = bigint;
export type ProductId = bigint;
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [string, string, string, string, bigint, bigint, bigint, number, string],
    ProductId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllInquiries' : ActorMethod<[], Array<CustomerInquiry>>,
  'getAllProducts' : ActorMethod<[], Array<FabricProduct>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProduct' : ActorMethod<[ProductId], FabricProduct>,
  'initializeSampleProducts' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitInquiry' : ActorMethod<
    [string, string, string, [] | [string], ProductId, bigint, string],
    InquiryId
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];