/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InquiryId = IDL.Nat;
export const Time = IDL.Int;
export const CustomerInquiry = IDL.Record({
  'id' : InquiryId,
  'customerName' : IDL.Text,
  'productId' : ProductId,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'companyName' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'quantityRequired' : IDL.Nat,
});
export const FabricProduct = IDL.Record({
  'id' : ProductId,
  'minOrderQuantity' : IDL.Nat,
  'weightGSM' : IDL.Nat,
  'fabricType' : IDL.Text,
  'widthCM' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'imageFilename' : IDL.Text,
  'description' : IDL.Text,
  'pricePerMeter' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Text,
      ],
      [ProductId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(CustomerInquiry)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(FabricProduct)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProduct' : IDL.Func([ProductId], [FabricProduct], ['query']),
  'initializeSampleProducts' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitInquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        ProductId,
        IDL.Nat,
        IDL.Text,
      ],
      [InquiryId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InquiryId = IDL.Nat;
  const Time = IDL.Int;
  const CustomerInquiry = IDL.Record({
    'id' : InquiryId,
    'customerName' : IDL.Text,
    'productId' : ProductId,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'companyName' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'quantityRequired' : IDL.Nat,
  });
  const FabricProduct = IDL.Record({
    'id' : ProductId,
    'minOrderQuantity' : IDL.Nat,
    'weightGSM' : IDL.Nat,
    'fabricType' : IDL.Text,
    'widthCM' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'imageFilename' : IDL.Text,
    'description' : IDL.Text,
    'pricePerMeter' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Text,
        ],
        [ProductId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(CustomerInquiry)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(FabricProduct)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProduct' : IDL.Func([ProductId], [FabricProduct], ['query']),
    'initializeSampleProducts' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitInquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          ProductId,
          IDL.Nat,
          IDL.Text,
        ],
        [InquiryId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };